name: 'Close a GitHub Issue'
description: 'Close a GitHub issue.'
inputs:
  token:
    description: 'The GitHub access token.'
    required: true
  issue_number:
    description: 'The number of the issue.'
    required: true
outputs:
  issue:
    description: 'The closed issue.'
runs:
  using: 'node12'
  main: 'index.js'