name: 'Checks GitHub Issue'
description: 'Checks if the issue has a label.'
inputs:
  label:
    description: 'The label to check for on the issue.'
    required: true
outputs:
  exists:
    description: 'True if the label exists, otherwise false.'
runs:
  using: 'node12'
  main: 'index.js'